[phases.build]
cmds = [
  "echo 'Building FastAPI backend...'",
  "cd modec/project/backend",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "cd modec/project/backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "/app/modec/project/backend"